package Bibliography.editor;

/*Generated by MPS */

import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuComponent;
import jetbrains.mps.nodeEditor.cellMenu.SubstituteInfoPartExt;
import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuPart_Generic_Group;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Arrays;

public class Authors extends AbstractCellMenuComponent {
  public Authors() {
    super(new SubstituteInfoPartExt[]{new Authors.Author_generic_cellMenu_8f36s4_a0()});
  }
  public static class Author_generic_cellMenu_8f36s4_a0 extends AbstractCellMenuPart_Generic_Group {
    public Author_generic_cellMenu_8f36s4_a0() {
    }
    public List<?> createParameterObjects(SNode node, IOperationContext operationContext, EditorContext editorContext) {
      return ListSequence.fromListAndArray(new ArrayList<String>(), "Donald", "Andrew", "Brian", "Dennis");
    }
    protected void handleAction(Object parameterObject, SNode node, SModel model, IOperationContext operationContext, EditorContext editorContext) {
      this.handleAction_impl((String) parameterObject, node, model, operationContext, editorContext);
    }
    public void handleAction_impl(String parameterObject, SNode node, SModel model, IOperationContext operationContext, EditorContext editorContext) {
      SNode p;
      p = SNodeOperations.replaceWithAnother(node, SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, "Bibliography.structure.Person"))));

      SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290aL, "firstname"), parameterObject);
      switch (Arrays.binarySearch(stringSwitchCases_8f36s4_a0e0d1, parameterObject)) {
        case 3:
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290cL, "lastname"), "Knuth");
        case 0:
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290fL, "middlename"), "S.");
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290cL, "lastname"), "Tennenbaum");
        case 1:
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290fL, "middlename"), "W.");
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290cL, "lastname"), "Kernigan");
        case 2:
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290fL, "middlename"), "M.");
          SPropertyOperations.set(p, MetaAdapterFactory.getProperty(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L, 0x56e0421a741e290cL, "lastname"), "Ritchie");
        default:
      }
    }
    public boolean isReferentPresentation() {
      return false;
    }
    public String getDescriptionText(Object parameterObject) {
      return this.getDescriptionText_internal((String) parameterObject);
    }
    public String getDescriptionText_internal(String parameterObject) {
      return "Add an author:" + parameterObject;
    }
  }
  private static String[] stringSwitchCases_8f36s4_a0e0d1 = new String[]{"Andrew", "Brian", "Dennis", "Donald"};
}
