package Bibliography.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAuthor = new ConceptDescriptorBuilder("Bibliography.structure.Author", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2909L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().alias("author", "").create();
  /*package*/ final ConceptDescriptor myConceptAuthorRef = new ConceptDescriptorBuilder("Bibliography.structure.AuthorRef", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f96L)).super_("Bibliography.structure.Author").super_(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2909L)).parents("Bibliography.structure.Author").parentIds(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2909L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(6260076163429707671L, "author", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L), false)).references("author").create();
  /*package*/ final ConceptDescriptor myConceptAuthorsElement = new ConceptDescriptorBuilder("Bibliography.structure.AuthorsElement", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2906L)).super_("Bibliography.structure.BiblioElement").super_(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).parents("Bibliography.structure.BiblioElement").parentIds(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).childDescriptors(new ConceptDescriptorBuilder.Link(6260076163429705991L, "authors", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2909L), true, true, false)).children(new String[]{"authors"}, new boolean[]{true}).alias("authors", "").create();
  /*package*/ final ConceptDescriptor myConceptBiblioElement = new ConceptDescriptorBuilder("Bibliography.structure.BiblioElement", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().alias("<element>", "a bibliographical element such as author, publication").create();
  /*package*/ final ConceptDescriptor myConceptBiblioRecord = new ConceptDescriptorBuilder("Bibliography.structure.BiblioRecord", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e28fbL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(6260076163429705982L, "elements", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L), true, true, false)).children(new String[]{"elements"}, new boolean[]{true}).alias("biblio-record", "A bibliographical record, article, web page, etc").create();
  /*package*/ final ConceptDescriptor myConceptBibliography = new ConceptDescriptorBuilder("Bibliography.structure.Bibliography", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e28f6L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(6260076163429705977L, "records", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e28fbL), true, true, false)).children(new String[]{"records"}, new boolean[]{true}).alias("bibliography", "a list of bibliographical records").create();
  /*package*/ final ConceptDescriptor myConceptConceptWithBehaviour = new ConceptDescriptorBuilder("Bibliography.structure.ConceptWithBehaviour", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x7723855064e36b26L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8584851895034800935L, "a"), new ConceptDescriptorBuilder.Prop(8584851895034800937L, "b"), new ConceptDescriptorBuilder.Prop(8584851895034800940L, "c")).properties("a", "b", "c").create();
  /*package*/ final ConceptDescriptor myConceptPerson = new ConceptDescriptorBuilder("Bibliography.structure.Person", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2f99L)).super_("Bibliography.structure.Author").super_(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2909L)).parents("Bibliography.structure.Author", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2909L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(6260076163429705994L, "firstname"), new ConceptDescriptorBuilder.Prop(6260076163429705999L, "middlename"), new ConceptDescriptorBuilder.Prop(6260076163429705996L, "lastname")).properties("firstname", "middlename", "lastname").alias("person", "").create();
  /*package*/ final ConceptDescriptor myConceptPublicationYear = new ConceptDescriptorBuilder("Bibliography.structure.PublicationYear", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2913L)).super_("Bibliography.structure.BiblioElement").super_(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).parents("Bibliography.structure.BiblioElement").parentIds(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(6260076163429706004L, "value")).properties("value").alias("publication-year", "The year record was published.").create();
  /*package*/ final ConceptDescriptor myConceptTitleElement = new ConceptDescriptorBuilder("Bibliography.structure.TitleElement", MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2901L)).super_("Bibliography.structure.BiblioElement").super_(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).parents("Bibliography.structure.BiblioElement").parentIds(MetaIdFactory.conceptId(0x271a8efddd204825L, 0x8ab3fbd398a83eddL, 0x56e0421a741e2900L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(6260076163429705988L, "value")).properties("value").alias("title element", "The title of a bibliographical record").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAuthor, myConceptAuthorRef, myConceptAuthorsElement, myConceptBiblioElement, myConceptBiblioRecord, myConceptBibliography, myConceptConceptWithBehaviour, myConceptPerson, myConceptPublicationYear, myConceptTitleElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0o, conceptFqName)) {
      case 0:
        return myConceptAuthor;
      case 1:
        return myConceptAuthorRef;
      case 2:
        return myConceptAuthorsElement;
      case 3:
        return myConceptBiblioElement;
      case 4:
        return myConceptBiblioRecord;
      case 5:
        return myConceptBibliography;
      case 6:
        return myConceptConceptWithBehaviour;
      case 7:
        return myConceptPerson;
      case 8:
        return myConceptPublicationYear;
      case 9:
        return myConceptTitleElement;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0o = new String[]{"Bibliography.structure.Author", "Bibliography.structure.AuthorRef", "Bibliography.structure.AuthorsElement", "Bibliography.structure.BiblioElement", "Bibliography.structure.BiblioRecord", "Bibliography.structure.Bibliography", "Bibliography.structure.ConceptWithBehaviour", "Bibliography.structure.Person", "Bibliography.structure.PublicationYear", "Bibliography.structure.TitleElement"};
}
